/** Constellation API — Express server with security middleware. */
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { z } from "zod";

import { config } from "./config.js";
import { composeQuery } from "./compose/compose.js";
import { getGraph } from "./data/load.js";
import { queryRouter } from "./routes/query.js";
import { ingestRouter } from "./routes/ingest.js";
import type { ActionCard, Narrative, QueryResponse } from "./types.js";

const app = express();

app.disable("x-powered-by");
app.use(helmet());
app.use(cors({ origin: config.webOrigin }));
app.use(express.json({ limit: "64kb" }));
app.use(
  "/api",
  rateLimit({
    windowMs: 60_000,
    max: 60,
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: "Too many requests — slow down." },
  }),
);

app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", iq: { foundry: config.foundry.live, work: config.workIq.live, fabric: config.fabricIq.live } });
});

// Base constellation for the initial render.
app.get("/api/graph", (_req, res) => {
  const graph = getGraph();
  res.json({
    nodes: graph.nodes.map((n) => ({ ...n, group: "context" })),
    links: graph.links,
  });
});

app.use("/api/query", queryRouter);
app.use("/api/ingest", ingestRouter);

// Export a shareable markdown summary. Blocked in safe-demo mode by design.
const ExportSchema = z.object({
  prompt: z.string().trim().min(1).max(2000),
  mode: z.enum(["pattern-hunt", "executive-story", "playbook-remix"]),
  safeDemo: z.boolean().optional().default(false),
});

app.post("/api/export", (req, res) => {
  const parsed = ExportSchema.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid request", details: parsed.error.flatten() });
    return;
  }
  if (parsed.data.safeDemo) {
    res.status(403).json({
      error: "Export is disabled in safe-demo mode to prevent publishing sensitive content.",
    });
    return;
  }
  try {
    const result = composeQuery(parsed.data);
    res.json({ markdown: renderMarkdown(result) });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Internal error";
    res.status(500).json({ error: message });
  }
});

function renderMarkdown(result: QueryResponse): string {
  const n: Narrative = result.narrative;
  const lines: string[] = [`# ${n.title}`, "", `_${n.summary}_`, ""];
  for (const s of n.segments) {
    const cites = s.citations.map((c) => `[${c.title}](${c.artifactPath})`).join(", ");
    lines.push(`- **(${s.confidence})** ${s.text}${cites ? `  \n  Sources: ${cites}` : ""}`);
  }
  lines.push("", "## Proposed actions", "");
  for (const a of result.actions as ActionCard[]) {
    lines.push(`- **${a.title}** — owner: ${a.owner}, due: ${a.dueDate} _(${a.confidence})_  \n  ${a.rationale}`);
  }
  lines.push("", "---", "_Generated by Constellation on synthetic data. No confidential information._");
  return lines.join("\n");
}

app.listen(config.port, () => {
  // eslint-disable-next-line no-console
  console.log(`Constellation API listening on http://localhost:${config.port} (web origin ${config.webOrigin})`);
});
